name: get_cli
description: Official CLI for GetXâ„¢ framework to build Flutter Applications easily
version: 0.11.2
homepage: https://github.com/jonataslaw/get_cli

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  get: get

dependencies:
  recase: ^3.0.0
  cli_menu: ^0.2.2
  archive: ^2.0.13
  ansicolor: ^1.0.2
  process_run: ^0.10.12+1
  http: ^0.12.2
  path: ^1.7.0
  yaml: ^2.2.1
  version: ^1.2.0
  intl: ^0.16.1


dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0